### ISSUE TITLE
error training my own dataset

### ISSUE THREAD

**Issue by kotaxyz** [sebastianstarke/AI4Animation#100]
i exported dataset of my own animation from unity but when i try to train it i give this error 

```
(DeepPhaseSubmission) C:\Users\Genesis\deep-motion\PyTorch\PAE>python Train.py
Loading Dataset/DataShape.txt
Loading Dataset/Sequences.txt
Generating Data Sequences
Data Sequences: 25650
Test Sequences: 250
Training Phases
Traceback (most recent call last):
  File "Train.py", line 142, in <module>
    yPred, latent, signal, params = network(train_batch)
  File "C:\Users\Genesis\anaconda3\envs\DeepPhaseSubmission\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Genesis\deep-motion\PyTorch\PAE\PAE.py", line 79, in forward
    y = y.reshape(y.shape[0], self.input_channels, self.time_range)
RuntimeError: shape '[32, 78, 121]' is invalid for input of size 441408

(DeepPhaseSubmission) C:\Users\Genesis\deep-motion\PyTorch\PAE>
```

note that i use the 2022 updated ai4animation

**Comment by sebastianstarke** [comment]
Did you doublecheck the number of joints and framerate, which may be different for your own dataset?

**Comment by kotaxyz** [comment]
thanks i will try it out

**Comment by kotaxyz** [comment]
and yes my character has 38 joints

**Comment by kotaxyz** [comment]
which section needs to be adjusted in the  Train.py file

**Comment by kotaxyz** [comment]
it worked by adjusting the joint number in the parameters thanks alot
